<?php

$install_lang["activate"] = "Активировать";
$install_lang["activity"] = "Активность";
$install_lang["admin_header_chats"] = "Чаты";
$install_lang["admin_panel"] = "Панель администратора";
$install_lang["chat"] = "Чат";
$install_lang["chat_height"] = "Высота";
$install_lang["chat_width"] = "Ширина";
$install_lang["deactivate"] = "Отключить";
$install_lang["flashchat_admin_panel_not_available"] = "К сожалению, панель администратора недоступна в бесплатной версии Free Chat Hosting Edition. Демо версию можно <a href=\"http://www.123flashchat.com/admin-panel-free.html\" target=\"_blank\">посмотреть здесь</a>.";
$install_lang["flashchat_by_flashchat_client_example"] = "Пример: http://hostxxx.123flashchat.com/group_name/";
$install_lang["flashchat_by_flashchat_client_note"] = "Обратите внимание: ссылка hosting chat для 123 PPV Software совпадает со ссылкой для 123 Flash Chat.";
$install_lang["flashchat_chat_server_mode"] = "Режим сервера";
$install_lang["flashchat_chat_server_mode_by_user"] = "123FlashChat Server Hosted By Your Own (ваш хостинг)";
$install_lang["flashchat_chat_server_mode_by_user_note"] = "Пожалуйста, сперва скачайте и установите 123FlashChat: <a href=\"http://www.123flashchat.com/download.html\" target=\"_blank\"> http://www.123flashchat.com/download.html</a>";
$install_lang["flashchat_chat_server_mode_by_flashchat"] = "123FlashChat Server Hosted By 123FlashChat (хостинг 123FlashChat)";
$install_lang["flashchat_chat_server_mode_by_flashchat_note"] = "В случае с <a href=\"http://www.123flashchat.com/host.html\" target=\"_blank\">платным хостингом</a> настройте Chat Client Location как указано в примере: http://host71200.123flashchat.com/wordpress/ <br><a href=\"http://www.123flashchat.com/host.html\" target=\"_blank\">Заплатить за хостинг</a>. <br> В случае с <a href=\"http://www.123flashchat.com/host/apply.php\" target=\"_blank\">пробным хостингом</a> настройте Chat Client Location как указано в примере: http://trial.123flashchat.com/yourhostname<br>Нужно заменить \"yourhostname\" на соответствующие данные ваших настроек <br><a href=\"http://www.123flashchat.com/host/apply.php\" target=\"_blank\">Включить пробный хостинг</a>";
$install_lang["flashchat_chat_server_mode_by_flashchat_free"] = "123FlashChat Server Hosted By 123FlashChat Free Of Charge (бесплатный хостинг от 123FlashChat)";
$install_lang["flashchat_chat_server_mode_by_flashchat_free_note"] = "Этот режим сервера предназначен для тестирования базовых функций, поддерживает только одну комнату, в нем отсутствует видео чат и доступ к панели администратора. Выберите режимы 1 или 2, чтобы воспользоваться функционалом в полной мере.";
$install_lang["flashchat_chatroom"] = "Комната чата";
$install_lang["flashchat_client_location"] = "Адрес клиента";
$install_lang["flashchat_client_type"] = "Тип клиента";
$install_lang["flashchat_client_type_flashchat"] = "Flash Chat";
$install_lang["flashchat_client_type_htmlchat"] = "HTML Chat";
$install_lang["flashchat_flash"] = "Flash";
$install_lang["flashchat_fullscreen"] = "Полный экран";
$install_lang["flashchat_html"] = "HTML";
$install_lang["flashchat_init_port_h"] = "HTTP порт";
$install_lang["flashchat_integration_url"] = "URL интеграции";
$install_lang["flashchat_integration_url_note"] = "Чтобы разрешить автоматическую авторизацию пользователей в 123FlashChat, в панели администратора 123FlashChat в разделе Server Settings > Integration > DataBase > URL > Edit установите URL, как показано ниже";
$install_lang["flashchat_language"] = "Язык";
$install_lang["flashchat_init_host"] = "Адрес сервера";
$install_lang["flashchat_init_port"] = "Порт сервера";
$install_lang["flashchat_server_type"] = "Тип сервера";
$install_lang["flashchat_server_type_flashchat"] = "123FlashChat";
$install_lang["flashchat_server_type_ppvsoftware"] = "123PPVSoftware";
$install_lang["flashchat_show_room_list"] = "Показывать список комнат";
$install_lang["flashchat_show_user_list"] = "Показывать список пользователей";
$install_lang["flashchat_skin"] = "Скин";
$install_lang["get_files"] = "Получить файлы чата";
$install_lang["install"] = "Установить";
$install_lang["installed"] = "Установлен";
$install_lang["name"] = "Чат";
$install_lang["no_files"] = "Файлы отсутствуют";
$install_lang["no_chats"] = "Установленные чаты отсутствуют";
$install_lang["set_installed"] = "Завершить установку";
$install_lang["settings"] = "Настройки";
$install_lang["status"] = "Статус";
